# Generated by Django 5.1.4 on 2025-03-05 02:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_school_lat_school_long_school_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
            ],
            options={
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="lower_name_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "Stock_cover",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="Books", to="core.author"
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="Books", to="core.course"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("code", "school"), name="unique_course_at_school"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                django.db.models.functions.text.Lower("title"), name="lower_title_idx"
            ),
        ),
    ]
