# Generated by Django 5.1.4 on 2025-03-11 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('isbn', models.CharField(max_length=64)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listing_images/')),
                ('sold', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Acceptable', 'Acceptable')], default='New', max_length=20)),
                ('location', models.CharField(choices=[('Local', 'Local'), ('Global', 'Global')], default='Local', max_length=64)),
                ('coursecode', models.CharField(blank=True, max_length=64, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
