# Generated by Django 5.1.4 on 2025-03-12 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_image_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
