# Generated by Django 5.1.5 on 2025-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_alter_listing_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='listing',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='coursecode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('Global', 'Global'), ('Local', 'Local')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
