# Generated by Django 5.1.4 on 2025-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
