# Generated by Django 5.1.4 on 2025-03-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listingimage_created_at_listingimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='order',
        ),
    ]
