# Generated by Django 5.1.4 on 2025-02-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="user",
            new_name="seller",
        ),
    ]
