# Generated by Django 5.1.4 on 2025-03-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_rename_user_listing_seller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="description",
            new_name="additional_details",
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("LN", "Like New"),
                    ("G", "Good"),
                    ("A", "Acceptable"),
                ],
                default="N",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(
                choices=[("L", "Local"), ("G", "Global")], default="L", max_length=64
            ),
        ),
    ]
