# Generated by Django 5.1.4 on 2025-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_rename_description_listing_additional_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Like New", "Like New"),
                    ("Good", "Good"),
                    ("Acceptable", "Acceptable"),
                ],
                default="New",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(
                choices=[("Local", "Local"), ("Global", "Global")],
                default="Local",
                max_length=64,
            ),
        ),
    ]
