# Generated by Django 5.1.4 on 2025-03-05 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_author_course_book_course_unique_course_at_school_and_more"),
        ("listings", "0007_rename_description_listing_additional_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="author",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="coursecode",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="title",
        ),
        migrations.AddField(
            model_name="listing",
            name="allows_local_pickup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="allows_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Listings",
                to="core.book",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("LN", "Like New"),
                    ("G", "Good"),
                    ("A", "Acceptable"),
                ],
                default="N",
                max_length=3,
            ),
        ),
    ]
