# Generated by Django 5.1.4 on 2025-03-05 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_remove_listing_author_remove_listing_coursecode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
