# Generated by Django 5.1.4 on 2025-03-14 04:57

import django.db.models.deletion
from django.db import migrations, models

def migrate_images(apps, schema_editor):
    """ Migrating DB data for listing images to move to seperated ListingImage """
    Listing = apps.get_model("listings", "Listing")
    ListingImage = apps.get_model("listings", "ListingImage")

    # For each Listing, move the image field into a new seperated ListingImage instance:
    for listing in Listing.objects.all():
        listing_img = ListingImage(listing=listing, image=listing.image)
        listing_img.save()


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_listing_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listing_images/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_images),
        migrations.RemoveField(
            model_name="listing",
            name="image",
        ),
    ]
