# Generated by Django 5.1.4 on 2025-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_listing_created_at_listing_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
