# Generated by Django 5.1.4 on 2025-03-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_subject_book_edition_book_subjects"),
        ("listings", "0012_listing_created_at_listing_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Listings",
                to="core.book",
            ),
        ),
    ]
