# Generated by Django 5.1.4 on 2025-03-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_alter_listing_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(
                choices=[("Local", "Local"), ("Global", "Global"), ("Both", "Both")],
                default="Local",
                max_length=64,
            ),
        ),
    ]
